version: '3.9'
services:
  development:
    container_name: app-03-meals
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - /workspaces/app-03-meals/node_modules
